name: abstractify
description: "A Text Based App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.2
  http: ^1.2.2
  file_picker: ^8.1.3
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  shared_preferences: ^2.5.1
  desktop_drop: ^0.4.3
  path: ^1.8.3
  image_size_getter: ^2.4.0
  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf

    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide.ttf
  assets:
    - assets/images/
    - assets/animations/
